package goemit

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"gode.dev/gode-compiler/internal/diagnostics"
	fast "gode.dev/gode-compiler/internal/frontend/ast"
	"gode.dev/gode-compiler/internal/ir"
	"gode.dev/gode-compiler/internal/names"
)

func Emit(mod ir.Module) (string, diagnostics.List) {
	e := emitter{
		mod:     mod,
		funcs:   map[string]ir.Declaration{},
		structs: map[string]ir.Declaration{},
	}
	for _, decl := range mod.Declarations {
		switch decl.Kind {
		case "function", "external_function":
			e.funcs[decl.Name] = decl
		case "struct":
			e.structs[decl.Name] = decl
		}
	}
	src := e.emitModule()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src, diagnostics.List{diagnostics.Errorf("", diagnostics.Position{Line: 1, Column: 1}, "GODE_CODEGEN_001", "generated Go is invalid: %v", err)}
	}
	return string(formatted), nil
}

type emitter struct {
	mod     ir.Module
	buf     bytes.Buffer
	funcs   map[string]ir.Declaration
	structs map[string]ir.Declaration
}

func (e *emitter) emitModule() string {
	e.line("// Code generated by godec; DO NOT EDIT.")
	e.line("")
	e.line("package %s", e.mod.PackageName)
	e.line("")
	needsContext := e.mod.UsesAsync
	needsErrgroup := e.needsErrgroup()
	if needsContext || needsErrgroup {
		e.line("import (")
		if needsContext {
			e.line("%q", "context")
		}
		if needsContext && needsErrgroup {
			e.line("")
		}
		if needsErrgroup {
			e.line("%q", "golang.org/x/sync/errgroup")
		}
		e.line(")")
		e.line("")
	}
	for _, decl := range e.mod.Declarations {
		switch decl.Kind {
		case "struct":
			e.emitStruct(decl)
		case "const":
			e.emitConst(decl)
		case "function":
			e.emitFunction(decl)
		}
	}
	return e.buf.String()
}

func (e *emitter) emitStruct(decl ir.Declaration) {
	e.line("type %s struct {", names.Exported(decl.Name))
	for _, field := range decl.Fields {
		goType := e.goType(field.Type)
		if field.Optional && !strings.HasPrefix(goType, "*") {
			goType = "*" + goType
		}
		tag := field.JSONName
		if tag == "" {
			tag = field.Name
		}
		if field.Optional {
			tag += ",omitempty"
		}
		e.line("%s %s `json:%q`", field.GoName, goType, tag)
	}
	e.line("}")
	e.line("")
}

func (e *emitter) emitConst(decl ir.Declaration) {
	if len(decl.Body) == 0 || decl.Body[0].Expr == nil {
		return
	}
	e.line("const %s %s = %s", decl.GoName, e.goType(decl.ReturnType), e.emitExpr(decl.Body[0].Expr, nil, nil))
	e.line("")
}

func (e *emitter) emitFunction(decl ir.Declaration) {
	params := make([]string, 0, len(decl.Params)+1)
	rename := map[string]string{}
	if decl.Async {
		params = append(params, "ctx context.Context")
	}
	for _, param := range decl.Params {
		goName := param.GoName
		if decl.Async && goName == "ctx" {
			goName = "godeCtx"
			rename[param.GoName] = goName
			rename[param.Name] = goName
		}
		params = append(params, fmt.Sprintf("%s %s", goName, e.goType(param.Type)))
	}
	ret := e.goType(decl.ReturnType)
	if decl.Async {
		ret = e.goType(decl.ReturnType.Inner)
		if ret == "" {
			ret = "error"
		} else {
			ret = fmt.Sprintf("(%s, error)", ret)
		}
	}
	if ret == "" {
		e.line("func %s(%s) {", decl.GoName, strings.Join(params, ", "))
	} else {
		e.line("func %s(%s) %s {", decl.GoName, strings.Join(params, ", "), ret)
	}
	e.emitStatements(decl.Body, decl, rename)
	e.line("}")
	e.line("")
}

func (e *emitter) emitStatements(stmts []fast.Statement, fn ir.Declaration, rename map[string]string) {
	returnType := fn.ReturnType
	if fn.Async && returnType != nil && returnType.Kind == "promise" {
		returnType = returnType.Inner
	}
	for i := 0; i < len(stmts); i++ {
		if fn.Async && isAwaitVar(stmts[i]) {
			j := i + 1
			groupNames := map[string]bool{stmts[i].Name: true}
			for j < len(stmts) && isAwaitVar(stmts[j]) && !exprUsesAny(stmts[j].Expr, groupNames) {
				groupNames[stmts[j].Name] = true
				j++
			}
			e.emitAwaitGroup(stmts[i:j], returnType, rename)
			i = j - 1
			continue
		}
		e.emitStatement(stmts[i], fn.Async, returnType, rename)
	}
}

func (e *emitter) emitStatement(stmt fast.Statement, async bool, returnType *fast.Type, rename map[string]string) {
	switch stmt.Kind {
	case "return":
		if async {
			if stmt.Expr == nil {
				e.line("return nil")
				return
			}
			if stmt.Expr.Kind == "await" {
				e.line("return %s", e.emitAsyncCall(stmt.Expr.Expr, rename))
				return
			}
			e.line("return %s, nil", e.emitExprWithExpected(stmt.Expr, returnType, rename))
			return
		}
		if stmt.Expr == nil {
			e.line("return")
			return
		}
		e.line("return %s", e.emitExprWithExpected(stmt.Expr, returnType, rename))
	case "var":
		if stmt.Type != nil {
			e.line("var %s %s = %s", stmt.Name, e.goType(stmt.Type), e.emitExpr(stmt.Expr, nil, rename))
		} else {
			e.line("%s := %s", stmt.Name, e.emitExpr(stmt.Expr, nil, rename))
		}
	case "if":
		e.line("if %s {", e.emitExpr(stmt.Expr, nil, rename))
		for _, inner := range stmt.Then {
			e.emitStatement(inner, async, returnType, rename)
		}
		if len(stmt.Else) > 0 {
			e.line("} else {")
			for _, inner := range stmt.Else {
				e.emitStatement(inner, async, returnType, rename)
			}
		}
		e.line("}")
	}
}

func (e *emitter) emitAwaitGroup(group []fast.Statement, returnType *fast.Type, rename map[string]string) {
	if len(group) == 1 {
		stmt := group[0]
		call := stmt.Expr.Expr
		e.line("%s, err := %s", stmt.Name, e.emitAsyncCall(call, rename))
		e.line("if err != nil {")
		e.emitZeroReturn(returnType)
		e.line("}")
		return
	}
	e.line("g, ctx := errgroup.WithContext(ctx)")
	for _, stmt := range group {
		e.line("var %s %s", stmt.Name, e.goType(stmt.Type))
		e.line("g.Go(func() error {")
		e.line("var err error")
		e.line("%s, err = %s", stmt.Name, e.emitAsyncCall(stmt.Expr.Expr, rename))
		e.line("return err")
		e.line("})")
	}
	e.line("if err := g.Wait(); err != nil {")
	e.emitZeroReturn(returnType)
	e.line("}")
}

func (e *emitter) emitZeroReturn(returnType *fast.Type) {
	if returnType == nil || (returnType.Kind == "primitive" && returnType.Name == "void") {
		e.line("return err")
		return
	}
	e.line("var zero %s", e.goType(returnType))
	e.line("return zero, err")
}

func (e *emitter) emitAsyncCall(expr *fast.Expr, rename map[string]string) string {
	if expr == nil || expr.Kind != "call" {
		return e.emitExpr(expr, nil, rename)
	}
	args := make([]string, 0, len(expr.Args)+1)
	args = append(args, "ctx")
	for i := range expr.Args {
		args = append(args, e.emitExpr(&expr.Args[i], nil, rename))
	}
	return fmt.Sprintf("%s(%s)", e.emitExpr(expr.Callee, nil, rename), strings.Join(args, ", "))
}

func (e *emitter) emitExprWithExpected(expr *fast.Expr, expected *fast.Type, rename map[string]string) string {
	if expr != nil && expr.Kind == "object" && expected != nil {
		return e.emitObjectLiteral(expr, expected, rename)
	}
	return e.emitExpr(expr, expected, rename)
}

func (e *emitter) emitExpr(expr *fast.Expr, expected *fast.Type, rename map[string]string) string {
	if expr == nil {
		return ""
	}
	switch expr.Kind {
	case "identifier":
		if renamed, ok := rename[expr.Name]; ok {
			return renamed
		}
		if fn, ok := e.funcs[expr.Name]; ok {
			return fn.GoName
		}
		return expr.Name
	case "number", "string", "boolean":
		return expr.Value
	case "null", "undefined":
		return "nil"
	case "member":
		return fmt.Sprintf("%s.%s", e.emitExpr(expr.Object, nil, rename), names.Exported(expr.Property))
	case "binary":
		return fmt.Sprintf("%s %s %s", e.emitExpr(expr.Left, nil, rename), goOp(expr.Op), e.emitExpr(expr.Right, nil, rename))
	case "unary":
		return fmt.Sprintf("%s%s", expr.Op, e.emitExpr(expr.Expr, nil, rename))
	case "call":
		args := make([]string, 0, len(expr.Args))
		for i := range expr.Args {
			args = append(args, e.emitExpr(&expr.Args[i], nil, rename))
		}
		return fmt.Sprintf("%s(%s)", e.emitExpr(expr.Callee, nil, rename), strings.Join(args, ", "))
	case "await":
		return e.emitAsyncCall(expr.Expr, rename)
	case "object":
		return e.emitObjectLiteral(expr, expected, rename)
	default:
		return ""
	}
}

func (e *emitter) emitObjectLiteral(expr *fast.Expr, expected *fast.Type, rename map[string]string) string {
	typeName := ""
	if expected != nil {
		if expected.Kind == "reference" {
			typeName = names.Exported(expected.Name)
		}
	}
	entries := make([]string, 0, len(expr.Entries))
	for _, entry := range expr.Entries {
		entries = append(entries, fmt.Sprintf("%s: %s", names.Exported(entry.Key), e.emitExpr(entry.Value, nil, rename)))
	}
	if typeName == "" {
		return fmt.Sprintf("struct{%s}{%s}", "", strings.Join(entries, ", "))
	}
	return fmt.Sprintf("%s{%s}", typeName, strings.Join(entries, ", "))
}

func (e *emitter) goType(t *fast.Type) string {
	if t == nil {
		return ""
	}
	switch t.Kind {
	case "primitive":
		switch t.Name {
		case "string":
			return "string"
		case "number":
			return "float64"
		case "boolean":
			return "bool"
		case "void":
			return ""
		case "null", "undefined":
			return "any"
		}
	case "reference":
		return names.Exported(t.Name)
	case "array":
		return "[]" + e.goType(t.Inner)
	case "record":
		return fmt.Sprintf("map[%s]%s", e.goType(t.Key), e.goType(t.Value))
	case "nullable":
		return "*" + e.goType(t.Inner)
	case "promise":
		return e.goType(t.Inner)
	}
	return "any"
}

func (e *emitter) line(format string, args ...any) {
	if len(args) == 0 {
		e.buf.WriteString(format)
	} else {
		fmt.Fprintf(&e.buf, format, args...)
	}
	e.buf.WriteByte('\n')
}

func isAwaitVar(stmt fast.Statement) bool {
	return stmt.Kind == "var" && stmt.Expr != nil && stmt.Expr.Kind == "await"
}

func (e *emitter) needsErrgroup() bool {
	for _, decl := range e.mod.Declarations {
		if !decl.Async {
			continue
		}
		for i := 0; i < len(decl.Body); i++ {
			if !isAwaitVar(decl.Body[i]) {
				continue
			}
			groupNames := map[string]bool{decl.Body[i].Name: true}
			size := 1
			for j := i + 1; j < len(decl.Body) && isAwaitVar(decl.Body[j]) && !exprUsesAny(decl.Body[j].Expr, groupNames); j++ {
				groupNames[decl.Body[j].Name] = true
				size++
			}
			if size > 1 {
				return true
			}
		}
	}
	return false
}

func exprUsesAny(expr *fast.Expr, names map[string]bool) bool {
	if expr == nil {
		return false
	}
	if expr.Kind == "identifier" && names[expr.Name] {
		return true
	}
	if exprUsesAny(expr.Expr, names) || exprUsesAny(expr.Left, names) || exprUsesAny(expr.Right, names) || exprUsesAny(expr.Object, names) || exprUsesAny(expr.Callee, names) {
		return true
	}
	for i := range expr.Args {
		if exprUsesAny(&expr.Args[i], names) {
			return true
		}
	}
	for _, entry := range expr.Entries {
		if exprUsesAny(entry.Value, names) {
			return true
		}
	}
	return false
}

func goOp(op string) string {
	switch op {
	case "===":
		return "=="
	case "!==":
		return "!="
	default:
		return op
	}
}
