// Code generated by godec; DO NOT EDIT.

package api

import (
	"context"

	"golang.org/x/sync/errgroup"
)

type User struct {
	ID string `json:"id"`
}

type Profile struct {
	ID string `json:"id"`
}

type UserBundle struct {
	User    User    `json:"user"`
	Profile Profile `json:"profile"`
}

func LoadBundle(ctx context.Context, id string) (UserBundle, error) {
	g, ctx := errgroup.WithContext(ctx)
	var user User
	g.Go(func() error {
		var err error
		user, err = FetchUser(ctx, id)
		return err
	})
	var profile Profile
	g.Go(func() error {
		var err error
		profile, err = FetchProfile(ctx, id)
		return err
	})
	if err := g.Wait(); err != nil {
		var zero UserBundle
		return zero, err
	}
	return UserBundle{User: user, Profile: profile}, nil
}
