// Code generated by godec; DO NOT EDIT.

package api

type User struct {
	ID     string  `json:"id"`
	Age    float64 `json:"age"`
	Active *bool   `json:"active,omitempty"`
}

func IsAdult(user User) bool {
	return user.Age >= 18
}
